[phases.setup]
nixPkgs = ["python312"]
aptPkgs = ["fontconfig"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "apt-get install -y fonts-nanum || true",
  "fc-cache -fv"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
